name: esqueleto-examples
version: '0.0.0.0'
category: Database
author: Fintan Halpenny
maintainer: fintan.halpenny@gmail.com
copyright: 2017, Chris Allen
license: BSD3
github: FintanH/esqueleto
extra-source-files:
- README.md
dependencies:
- base
- esqueleto
- persistent
- persistent-template
- persistent-sqlite
- text
- microlens
ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N
when:
- condition: flag(werror)
  ghc-options: -Werror

executables:
  blog-example:
    main: Blog.hs

flags:
  werror:
    description: "Treat warnings as errors"
    manual: true
    default: false
