name: esqueleto-examples
version: '0.0.0.0'
category: Database
author: Fintan Halpenny
maintainer: cma@bitemyapp.com
copyright: 2019, Chris Allen
license: BSD3
github: bitemyapp/esqueleto

extra-source-files:
- README.md

dependencies:
- base
- esqueleto
- persistent
- persistent-template
- persistent-postgresql
- mtl
- monad-logger
- monad-control
- transformers-base
- unliftio-core

ghc-options:
- '-Wall'
- '-threaded'
- '-rtsopts'
- '-with-rtsopts=-N'

when:
  - condition: flag(werror)
    ghc-options: '-Werror'

executables:
  blog-example:
    other-modules:
      - Blog
    main: Main.hs

flags:
  werror:
    description: "Treat warnings as errors"
    manual: true
    default: false
